services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    env_file: .env
    environment:
      - WEBUI_AUTH=true
      - ENABLE_OLLAMA=false
      - WEBUI_NAME=SQRD AI
      - SCARF_NO_ANALYTICS=true
      - DO_NOT_TRACK=true
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - /srv/docker/volumes/openwebui:/app/backend/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.sqrd.link`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls=true"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
