services:
    arcane:
        image: ghcr.io/getarcaneapp/arcane:latest
        container_name: arcane
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /srv/docker/volumes/arcane/data:/app/data
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Amsterdam
            - APP_URL=https://nastradamus.sqrd.link
            - ENCRYPTION_KEY=${ENCRYPTION_KEY}
            - JWT_SECRET=${JWT_SECRET}
            - DATABASE_URL=file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
        ports:
            - "3552:3552"
