version: "3.9"

secrets:
  semaphore_admin_pw:
    file: /srv/docker/secrets/semaphore_admin_password.txt
  semaphore_access_key_encryption:
    file: /srv/docker/secrets/semaphore_access_key_encryption.txt

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    networks:
      - proxy

    environment:
      SEMAPHORE_DB_DIALECT: bolt

      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN:-admin}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-Richard}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@sqrd.link}

      SEMAPHORE_ADMIN_PASSWORD_FILE: /run/secrets/semaphore_admin_pw
      SEMAPHORE_ACCESS_KEY_ENCRYPTION_FILE: /run/secrets/semaphore_access_key_encryption

      SEMAPHORE_WEB_ROOT: "https://semaphore.sqrd.link"

    volumes:
      - /srv/docker/volumes/semaphore/db:/var/lib/semaphore
      - /srv/docker/volumes/semaphore/config:/etc/semaphore
      - /srv/docker/volumes/semaphore/tmp:/tmp/semaphore
      - /srv/docker/volumes/semaphore/ansible-collections:/etc/ansible/collections

    secrets:
      - semaphore_admin_pw
      - semaphore_access_key_encryption

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.semaphore.rule=Host(`semaphore.sqrd.link`)"
      - "traefik.http.routers.semaphore.entrypoints=websecure"
      - "traefik.http.routers.semaphore.tls=true"
      # - "traefik.http.routers.semaphore.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
